### ISSUE TITLE
Firefox xbox window border is shown

### ISSUE THREAD

**Issue by gbrian** [m1k1o/neko#154] opened 2022-03-18 08:18 UTC
Hi,
Looks like the xbox application settings are not working. I noticed it recently
<img width="733" alt="image" src="https://user-images.githubusercontent.com/767180/158758210-3ae77179-2ed5-40a7-8f1f-e0b31357786b.png">

Anyone else?

**Comment by m1k1o** [comment] 2022-03-18 08:28
This looks like duplicate of this: https://github.com/m1k1o/neko/issues/152

**Comment by gbrian** [comment] 2022-03-18 10:52
Ok, I'll make some tests and see.

**Closed** 2022-03-18 20:49 UTC
