### ISSUE TITLE
Can't log back in if all users disconnect and audio device doesn't exist

### ISSUE THREAD

**Issue by darnfinecoffee** [m1k1o/neko#284] opened 2023-04-10 10:01 UTC
Hi,
Since v2.8, I can't seem to be able to log back in after one (or multiple) users connect, then all log out. The login prompt times out. A restart of the server is needed for it to work again.

For example:
user1 logs in -> user1 logs out => timeout when trying to log back in
user1 logs in -> user2 logs in -> user2 logs out => can still connect as long as user1 is connected
user1 logs in -> user2 logs in -> user2 logs out -> user3 logs in -> user1 logs out => can still connect as long as user3 is connected
user1 logs in -> user2 logs in -> user 2 logs out -> user1 logs out => timeout when trying to log in

Everything was working fine with v2.7 using the exact same config.

Logs from 2.8, connecting/disconnecting with one user:
```
 nurdism/m1k1o server v2.8.0
9:18AM INF preflight complete config=/etc/neko/neko.yaml debug=false logging=false
9:18AM INF starting neko server service=neko
9:18AM INF setting initial screen size module=desktop screen_size=1280x720@30
9:18AM INF using TCP MUX listener=0.0.0.0:60000 module=webrtc
9:18AM INF using UDP MUX module=webrtc port=60000
9:18AM INF webrtc starting ephemeral_port_range=59000-59100 ice_lite=true ice_servers="[{URLs:[stun:stun.l.google.com:19302] Username: Credential:<nil> CredentialType:password}]" module=webrtc nat_ips=[PublicIP]
9:18AM INF Listening TCP on 0.0.0.0:60000 module=webrtc submodule=pion subsystem=ice-tcp
9:18AM WRN http listening on neko.domain:8080 module=http
9:18AM INF neko ready service=neko
9:18AM INF creating pipeline codec=opus module=capture src="pulsesrc device=audio_output.monitor ! audio/x-raw,channels=2 ! audioconvert ! opusenc inband-fec=true bitrate=320000 ! appsink name=appsinkaudio" submodule=stream-sink video_id=audio
9:18AM INF first listener, starting module=capture submodule=stream-sink video_id=audio
9:18AM INF creating pipeline codec=vp8 module=capture src="ximagesrc display-name=:0.0 show-pointer=true use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! queue !  vp8enc target-bitrate=1996800 cpu-used=4 end-usage=cbr threads=4 deadline=1 undershoot=95 buffer-size=12288 buffer-initial-size=6144 buffer-optimal-size=9216 keyframe-max-dist=25 min-quantizer=4 max-quantizer=20  ! appsink name=appsinkvideo" submodule=stream-sink video_id=video
9:18AM INF first listener, starting module=capture submodule=stream-sink video_id=video
9:18AM INF signaling state changed to have-local-offer module=webrtc submodule=pion subsystem=pc
9:18AM WRN negotiation is needed module=webrtc
9:18AM ERR creating offer failed error="InvalidModificationError: invalid proposed signaling state transition: have-local-offer->SetLocal(offer)->have-local-offer" module=webrtc
9:18AM INF signal update - LocalCandidate id=Y-mFZcBPkcZTXi55U8F2XBWX4k4XKPWB module=session
9:18AM INF signal update - LocalCandidate id=Y-mFZcBPkcZTXi55U8F2XBWX4k4XKPWB module=session
9:18AM INF sent all ICECandidates module=webrtc
9:18AM INF signal update - RemoteAnswer id=Y-mFZcBPkcZTXi55U8F2XBWX4k4XKPWB module=session
9:18AM INF signaling state changed to stable module=webrtc submodule=pion subsystem=pc
9:18AM INF Setting new connection state: Checking module=webrtc submodule=pion subsystem=ice
9:18AM INF ICE connection state changed: checking module=webrtc submodule=pion subsystem=pc
9:18AM INF connection state has changed connection_state=checking module=webrtc
9:18AM INF Setting new connection state: Connected module=webrtc submodule=pion subsystem=ice
9:18AM INF ICE connection state changed: connected module=webrtc submodule=pion subsystem=pc
9:18AM INF connection state has changed connection_state=connected module=webrtc
9:18AM INF peer connection state changed: connected module=webrtc submodule=pion subsystem=pc
9:18AM INF peer connected id=Y-mFZcBPkcZTXi55U8F2XBWX4k4XKPWB module=webrtc
9:18AM WRN read message error error="websocket: close 1005 (no status)" module=websocket
9:18AM WRN Failed to accept RTP stream is already closed module=webrtc submodule=pion subsystem=pc
9:18AM WRN Failed to read from candidate tcp4 host [PublicIP]:60000: io: read/write on closed pipe module=webrtc submodule=pion subsystem=ice
9:18AM WRN Failed to accept RTCP stream is already closed module=webrtc submodule=pion subsystem=pc
9:18AM INF Setting new connection state: Closed module=webrtc submodule=pion subsystem=ice
9:18AM INF peer connection state changed: closed module=webrtc submodule=pion subsystem=pc
9:18AM INF ICE connection state changed: closed module=webrtc submodule=pion subsystem=pc
9:18AM INF connection state has changed connection_state=closed module=webrtc
9:18AM INF peer closed id=Y-mFZcBPkcZTXi55U8F2XBWX4k4XKPWB module=webrtc
```
Same thing but on 2.7:
```
 nurdism/m1k1o server v2.7.0 dev
9:14AM INF preflight complete config=/etc/neko/neko.yaml debug=false logging=false
9:14AM INF starting neko server service=neko
9:14AM INF setting initial screen size module=desktop screen_size=1280x720@30
9:14AM INF using TCP MUX listener=0.0.0.0:60000 module=webrtc
9:14AM WRN UDPMuxDefault should not listening on unspecified address, use NewMultiUDPMuxFromPort instead module=webrtc submodule=pion subsystem=ice-udp
9:14AM INF using UDP MUX listener=0.0.0.0:60000 module=webrtc
9:14AM INF webrtc starting ephemeral_port_range=59000-59100 ice_lite=true ice_servers="[{URLs:[stun:stun.l.google.com:19302] Username: Credential:<nil> CredentialType:password}]" module=webrtc nat_ips=[PublicIP]
9:14AM INF Listening TCP on 0.0.0.0:60000 module=webrtc submodule=pion subsystem=ice-tcp
9:14AM WRN http listening on neko.domain:8080 module=http
9:14AM INF neko ready service=neko
9:15AM INF creating pipeline codec=opus module=capture src="pulsesrc device=auto_null.monitor ! audio/x-raw,channels=2 ! audioconvert ! opusenc inband-fec=true bitrate=320000 ! appsink name=appsink" submodule=stream-sink video_id=audio
9:15AM INF first listener, starting module=capture submodule=stream-sink video_id=audio
9:15AM INF creating pipeline codec=vp8 module=capture src="ximagesrc display-name=:0.0 show-pointer=true use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! queue !  vp8enc target-bitrate=1996800 cpu-used=4 end-usage=cbr threads=4 deadline=1 undershoot=95 buffer-size=12288 buffer-initial-size=6144 buffer-optimal-size=9216 keyframe-max-dist=25 min-quantizer=4 max-quantizer=20  ! appsink name=appsink" submodule=stream-sink video_id=video
9:15AM INF first listener, starting module=capture submodule=stream-sink video_id=video
9:15AM INF signaling state changed to have-local-offer module=webrtc submodule=pion subsystem=pc
9:15AM INF sent all ICECandidates module=webrtc
9:15AM INF signal update - RemoteAnswer id=dyUB-wXo35CaQmE1BknxYpFCWAYvvYho module=session
9:15AM INF signaling state changed to stable module=webrtc submodule=pion subsystem=pc
9:15AM INF Setting new connection state: Checking module=webrtc submodule=pion subsystem=ice
9:15AM INF ICE connection state changed: checking module=webrtc submodule=pion subsystem=pc
9:15AM INF connection state has changed connection_state=checking module=webrtc
9:15AM INF Setting new connection state: Connected module=webrtc submodule=pion subsystem=ice
9:15AM INF ICE connection state changed: connected module=webrtc submodule=pion subsystem=pc
9:15AM INF connection state has changed connection_state=connected module=webrtc
9:15AM INF peer connection state changed: connected module=webrtc submodule=pion subsystem=pc
9:15AM INF peer connected id=dyUB-wXo35CaQmE1BknxYpFCWAYvvYho module=webrtc
9:15AM WRN read message error error="websocket: close 1005 (no status)" module=websocket
9:15AM WRN Failed to accept RTP stream is already closed module=webrtc submodule=pion subsystem=pc
9:15AM INF Setting new connection state: Closed module=webrtc submodule=pion subsystem=ice
9:15AM INF peer connection state changed: closed module=webrtc submodule=pion subsystem=pc
9:15AM WRN Failed to accept RTCP stream is already closed module=webrtc submodule=pion subsystem=pc
9:15AM INF ICE connection state changed: closed module=webrtc submodule=pion subsystem=pc
9:15AM INF connection state has changed connection_state=closed module=webrtc
9:15AM INF peer closed id=dyUB-wXo35CaQmE1BknxYpFCWAYvvYho module=webrtc
9:15AM INF destroying pipeline module=capture submodule=stream-sink video_id=audio
9:15AM INF last listener, stopping module=capture submodule=stream-sink video_id=audio
9:15AM INF destroying pipeline module=capture submodule=stream-sink video_id=video
9:15AM INF last listener, stopping module=capture submodule=stream-sink video_id=video
9:15AM INF destroying session module=session session_id=dyUB-wXo35CaQmE1BknxYpFCWAYvvYho
```
Seems like the only difference is `Failed to read from candidate tcp4 host [PublicIP]:60000: io: read/write on closed pipe module=webrtc submodule=pion subsystem=ice`, maybe that's related?

My config file:
```
screen: "1280x720@30"
max_fps: 30
video_codec: "vp8"
video_bitrate: 2000
hwenc: "none"
audio_codec: "opus"
audio_bitrate: 256

password: "password"
password_admin: "admin"

bind: "neko.domain:8080"
udpmux: "60000"
tcpmux: "60000"
nat1to1: "[PublicIP]"
icelite: true

display: ":0.0"
static: "/usr/share/neko/dist"
```
The same thing happens no matter if I use the udpmux or epr setting.
I am running Neko directly on an Alpine v3.17 VM, without docker, with nginx as reverse proxy.

**Comment by m1k1o** [comment] 2023-04-10 10:49
I can't seem to replicate this. I also got the same error `Failed to read from candidate tcp4 host [PublicIP]:60000: io: read/write on closed pipe module=webrtc submodule=pion subsystem=ice` but I was able to log in and log out at any time.

What you describe looks like gstreamer has problems with starting or stopping pipeline. Because pipeline is started when first user joins. When others join meanwhile, it is still running. When the last user leaves, it stops both pipelines (audio and video). It looks like there might be some sort of blocking happening when stopping gstreamer pipeline that subsequently blocks whole server and nobody can join.

Could you try changing screen size? That also restarts gstreamer pipeline. If neko freezes after, then its problem with gstreamer.

Additionally, could you add `debug: true` to get more info? And with debug mode turn off please try to log in, log out and again log in.

**Comment by m1k1o** [comment] 2023-04-10 11:42
That means creating/destroying pipeline alone is working correctly.

I see `first listener, starting` where it starts the pipeline, but i am missing `last listener, stopping`. So after last user left the room, pipeline was not stopped. But it maybe tried to do so and ended up somehow blocked.

I also do not see `destroying session`, basically last 5 messages from your v2.7 that are not in v2.8:

```
9:15AM INF destroying pipeline module=capture submodule=stream-sink video_id=audio
9:15AM INF last listener, stopping module=capture submodule=stream-sink video_id=audio
9:15AM INF destroying pipeline module=capture submodule=stream-sink video_id=video
9:15AM INF last listener, stopping module=capture submodule=stream-sink video_id=video
9:15AM INF destroying session module=session session_id=dyUB-wXo35CaQmE1BknxYpFCWAYvvYho
```

If you don't log out only close the tab, does it happen? Or have you meant by logging out just closing the tab?

**Comment by darnfinecoffee** [comment] 2023-04-10 11:56
> If you don't log out only close the tab, does it happen? Or have you meant by logging out just closing the tab?
Yes, it still happens. Closing the tab or clicking on "log out" seems to make no difference.

**Comment by innerop** [comment] 2023-04-10 18:28
Sorry to interject here, but is this happening for both EPR and MUX based setups?

**Comment by m1k1o** [comment] 2023-04-10 18:50
> The same thing happens no matter if I use the udpmux or epr setting.

@innerop yes, as stated by the author and i also tried both. Though I still cannot replicate it.

**Comment by innerop** [comment] 2023-04-10 19:01
Ok, I'm about to start it and see, so I'll give it a try and see.  My instance is hosted in the public cloud, not sure if that makes a difference. I'm also not sure of choice of browser makes a difference. I've set mine to google-chrome

**Comment by innerop** [comment] 2023-04-10 19:03
Is there a changelog or tagged releases so we can see what changed in v2.8?

**Comment by innerop** [comment] 2023-04-10 19:22
@m1k1o I can't replicate it either. 

But I have lots of questions now that I got it up and running. First, let's see what changed in v2.8. I am fluent in Go, JS, and WebRTC, so I might be able to help.

**Comment by m1k1o** [comment] 2023-04-10 19:55
@innerop here is diff what changed between [v2.7...v2.8](https://github.com/m1k1o/neko/compare/v2.7...v2.8.0). I suspect that [this bigger refactoring](https://github.com/m1k1o/neko/commit/5690a849e211026d687b8635c32fde638def366d) could be root of this problems, since we added lots of channels and they might block if used incorrectly or in some rare edge case.

@darnfinecoffee could you check please if `v2.7.1` works and if `v2.7.2` does not work anymore? So that we can narrow it down to the refactoring.

**Comment by darnfinecoffee** [comment] 2023-04-10 20:29
I've identified the problematic commit! Seems like 0dd9597 is what causes the issue. Adding the `load-module` line from that commit to my pulseaudio config seems to fix the issue.

**Comment by m1k1o** [comment] 2023-04-10 20:36
Great! So its caused by audio, that means also audio was not working for you. You could also revert to the old one by adding `device: auto_null.monitor` to your config.

@innerop it can be reproduced by setting device to something that does not exist e.g. `-e "NEKO_DEVICE=foo"`. 

It would be still interesting what causes the deadlock, but its probably gstreamer pipeline that cannot stop. When changing screen it stops only video pipeline, so it makes sense.

**Comment by innerop** [comment] 2023-04-10 21:53
The above would go here:

gst/pipelines/

func NewAudioPipeline(rtpCodec codec.RTPCodec, device string, pipelineSrc string, bitrate uint) (string, error) {
    // Check if the audio device is available
    if !checkAudioDeviceAvailable(device) {
        return "", fmt.Errorf("audio device %s not available", device)
    }

    // Rest of the NewAudioPipeline function...
}

**Comment by m1k1o** [comment] 2023-04-10 22:20
@innerop Thank you for the suggestion.

I am more concerned about why gstreamer did not complain that the audio device does not exist. When trying to set non-existing display `-e "NEKO_DISPLAY=foo"` it does not work, again does not produce any error, but does not freeze.

Maybe adding `context.Context` or at least some timeout to the destroy function would be a good solution.

https://github.com/m1k1o/neko/blob/b2080649ea50d942c3e9887813d867edbfc21052/server/internal/capture/gst/gst.go#L96-L105

But that could cause memory leaks in C code when not destroyed properly.

I tried locally starting gstreamer pipeline with nonexisting device and it fails immediatly. Maybe we did not catch that error and we still think that pipeline is running although is not and we attempt to destroy it what causes deadlock.

```
$ gst-launch-1.0 pulsesrc device=foo ! audio/x-raw,channels=2 ! audioconvert ! opusenc inband-fec=true bitrate=128000 ! autoaudiosink
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstPulseSrcClock
ERROR: from element /GstPipeline:pipeline0/GstPulseSrc:pulsesrc0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:pulsesrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.000106250
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by innerop** [comment] 2023-04-11 00:26
yes, agreed, always best to fix the error handling than to try and avoid creating the error (since it can happen for another reason) ... good idea... but at least it's not preventing the proper use of the app

**Closed** 2023-09-07 19:24 UTC
Labels: bug
